# Deep Learning with PyTorch: A 60 Minute Blitz

Goal of this tutorial:
- Understand PyTorch’s Tensor library and neural networks at a high level.
- Train a small neural network to classify images.

## Part 1: What is PyTorch?

It’s a Python-based scientific computing package targeted at two sets of audiences:
- A replacement for NumPy to use the power of GPUs.
- A deep learning research platform that provides maximum flexibility and speed.

### Tensors

In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
x

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
x = torch.rand(5, 3)
x

tensor([[0.2767, 0.3850, 0.0501],
        [0.3540, 0.0694, 0.5470],
        [0.9220, 0.9617, 0.9602],
        [0.3997, 0.2570, 0.6832],
        [0.2253, 0.4583, 0.8994]])

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.2154, -1.0856, -0.0524],
        [-0.8335,  0.1730,  0.2780],
        [-1.1213, -0.3203, -1.3432],
        [-0.6631,  0.2045,  1.3517],
        [-0.5152,  0.3949, -0.3795]])

In [10]:
x.size()

torch.Size([5, 3])

In [11]:
x.shape

torch.Size([5, 3])

### Operations

In [12]:
y = torch.rand(5, 3)
x + y

tensor([[ 0.7282, -0.9236,  0.0731],
        [-0.4376,  1.1511,  0.5395],
        [-0.4669,  0.2490, -0.4299],
        [ 0.2802,  0.2184,  2.1776],
        [-0.1772,  0.7074, -0.1926]])

In [13]:
torch.add(x, y)

tensor([[ 0.7282, -0.9236,  0.0731],
        [-0.4376,  1.1511,  0.5395],
        [-0.4669,  0.2490, -0.4299],
        [ 0.2802,  0.2184,  2.1776],
        [-0.1772,  0.7074, -0.1926]])

In [14]:
y.add_(x)

tensor([[ 0.7282, -0.9236,  0.0731],
        [-0.4376,  1.1511,  0.5395],
        [-0.4669,  0.2490, -0.4299],
        [ 0.2802,  0.2184,  2.1776],
        [-0.1772,  0.7074, -0.1926]])

Note: Any operation that mutates a tensor in-place is post-fixed with an __. For example: x.copy_(y), x.t_(), will change x.

Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)

x, y, z

(tensor([[ 0.2029, -1.3536, -0.7460,  0.2445],
         [ 1.1687,  0.4842,  0.4997, -0.2441],
         [-1.8027,  0.8770, -0.0203,  2.0350],
         [ 2.2850, -0.1980,  0.1933, -0.3137]]),
 tensor([ 0.2029, -1.3536, -0.7460,  0.2445,  1.1687,  0.4842,  0.4997, -0.2441,
         -1.8027,  0.8770, -0.0203,  2.0350,  2.2850, -0.1980,  0.1933, -0.3137]),
 tensor([[ 0.2029, -1.3536, -0.7460,  0.2445,  1.1687,  0.4842,  0.4997, -0.2441],
         [-1.8027,  0.8770, -0.0203,  2.0350,  2.2850, -0.1980,  0.1933, -0.3137]]))

If you have a one element tensor, use .item() to get the value as a Python number:

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.5261])
2.5260744094848633


### NumPy Bridge

In [18]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [19]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [20]:
a.add_(1)
a, b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [21]:
import numpy as np

In [22]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [24]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu'. torch.double))